language: node_js
install:
- npm install -g codecov
- yarn --ignore-engines
node_js:
- 10
script:
- yarn lint
- yarn test
- codecov
- yarn build
cache: yarn
deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on:
    branch: auto-deploy
  email: im.lezhi@gmail.com
  api_key:
    secure: IsnM+XB6wOcU0Q7jxfmd77QIjUqOchzXN8+yPjgjnZJzDmatkhr4hswTGV2XKR5VjfCrkJCPo2VViK9xw4tnWB20iaSmGjZARWrAsQNoGvDjvJfhpMzE6aY6DAU6XeRRt7sRRHARVJe440ui5AuIn1feVtrjY98kyLhMLcCJIgSy75E7pdEAbWSDxaCaHN93B0EJNCU2ggi+KwgwUj+KCH1Jl0PYbn8/We7A9H+PGKWjPdp88DWDBx8xhuEu6w71WjIQN+5Z/o5NBIHl1Vk6BXaMFGLjI5qskbiV1gRGlixpNxrKKWEaEcwrFxflCQClBPdCV1P67ZKztndO3GuAnDXsjgDfFyFMfp4YXkKoyn2niL7Fnw6LwaETmKHDwCv31lr51IglPcZSIADVYihVzFwf2n62mXvodAijdQLQ/6GgpxYAg+m1s+pfdO4oXRG7MXPY5O0bYjQV76NhB10ooRlzVrSZ3wRJPAD8tf2zh4QlpqmAwaY/vf+sjviO2qRVRZNRx0vZ5ti+IqHYFmz2rOpc1YZ3ONtSdDQLVaRSiWwsfBu7DdkNIrIYi1XKA/Xjpjo9AgKZONP9Sbo20jMvQvt7NXzJHaZuaWjhjf5PXtGqOLDUWj0FlOyM/07H4EkpsHjussYsXyelmGK2rv+hevfV7YsC6WTB4SnDnaEjw44=
