language: node_js
install:
  - npm install -g codecov
  - yarn --ignore-engines
node_js:
  - 8
script:
  - export CODECOV_TOKEN="e54def3d-0ecd-4124-923c-d8a1085b0970"
  - npm run lint
  - npm run test
  - fossa
  - codecov
cache: yarn